### PR TITLE
Migrate from MPL 2.0 to MIT license

### PR DESCRIPTION
**Pull request by jessieay**
https://opensource.org/licenses/MIT

### CODE REVIEW

**Comment by jessieay** [comment]
@potatosalad should this be a PR to `develop` or OK on `master` ? Looks like former is the more updated branch but not sure which you are cutting releases from.

**Comment by potatosalad** [comment]
@jessieay I'll actually merge it into `develop` first, get everything prepared for the new version before cutting a new release on `master`.

I'll get the new release cut in the next couple of days and will close this PR once it's merged into `master`.

**Comment by jessieay** [comment]
@potatosalad OK, just LMK if there is anything I can do with this PR to make your life easier :)

**Comment by jessieay** [comment]
Hi! Just wanted to follow up and see if there is anything I can do to be helpful with this PR? I can't merge anything in this repo but I could open a new PR on `develop` if that makes things easier. Also not sure if the failing CI is a problem or just related to some stuff that hasn't made it from `develop` to `master`

**Comment by potatosalad** [comment]
@jessieay Your PR was merged into the `develop` branch already [here](https://github.com/potatosalad/ruby-jose/commit/ff5ea820a14348286b6576103d46b8226c780907). GitHub just doesn't close the PR until `develop` gets merged into `master`, if that makes sense.

There are some half-finished features on `develop` currently causing the CI failures which I should be wrapping up soon (adding support for ChaCha20-Poly1305 encryption, XChaCha20-Poly1305 encryption, fixed some RSA-PSS compatibility issues, AES-GCM/C20PKW/XC20PKW key-wrapping for ECDH-ES/PBES2 encryption, and support for ECDH-1PU).

This whole `master`/`develop` pattern is a historical relic from 2014-2015 or so when I originally put this project together and I'm no longer doing this with new projects due to the mess it can result in with trying to merge things into `master` in a timely manner.

**Comment by jessieay** [comment]
Hi there @potatosalad ! Just checking in on this. Can I help you with any of those half-finished features you mentioned? Looks very close according to the latest CI build but I haven't dug deep enough to know the size of the effort required to get it all 🍏  https://travis-ci.org/github/potatosalad/ruby-jose/builds/710940675

Happy to help however I can!

**Comment by jessieay** [comment]
Hi! any chance we will be seeing a new release of this gem with the MIT license? Otherwise we may have to find another solution on our side. I know you are busy and OSS can be a lot :( Let me know how I can help!

**Pull request merged**
